### ISSUE TITLE
[Bug] Not all hacks revert

### ISSUE THREAD

**Issue by sanelkukic** [ASHTeam/ash-aio-2#1]
Using the Revert button after applying certain hacks will cause it to fail. This bug still exists in v2.0.0.1, planned to get fixed by v2.0.0.4 or earlier.

**Note**: If you're gonna make an issue about this, please don't. It will be closed and marked as a duplicate.

**Comment by sanelkukic** [comment]
Should be fixed by version 2.0.0.1 or 2.0.0.2

**Comment by sanelkukic** [comment]
Closing because it's added to the project Bug Reports, fix in progress

**Comment by sanelkukic** [comment]
Issue doesn't really need fixing, Revert is fine as is

**Comment by v1tal** [comment]
its not fine lol you haven't added addresses for the new hacks

**Comment by v1tal** [comment]
i'll work on it

**Comment by SLIPotter** [comment]
my revert wont work

**Comment by SLIPotter** [comment]
so thats 2

**Comment by sanelkukic** [comment]
#4 fixed
