### ISSUE TITLE
Plans for AshAIO

### ISSUE THREAD

**Issue by sanelkukic** [ASHTeam/ash-aio-2#2]
What I want to do with AshAIO is:

- [ ] Make an Android version of the program
- [ ] Add GitHub API integration so that users can submit issues from within the program and more.
- [ ] Make the updater automatically download the newest version of the AIO if needed instead of making the user manually go to GitHub to download it.
- [ ] Make a AshAIO site where users can go to download AshAIO,  join the ASH Team Discord, etc. ASH Team members would get access to a Admin panel that allows them to do stuff like make announcements, view the most/least used hacks, edit the site, push updates, etc.
- [ ] AshAIO for Linux/Ubuntu/CentOS

As you can see I have a lot of plans for AshAIO. Lemme know what you think in the comments below.

**Comment by v1tal** [comment]
ios dev needs a mac, fuck that tbh, even tho i would love it

**Comment by SLIPotter** [comment]
man ios ash would be great

**Comment by v1tal** [comment]
not happening

**Comment by sanelkukic** [comment]
Removed iOS app dev from the list

**Comment by Monotek18** [comment]
This on android...
need !

**Comment by v1tal** [comment]
possibly

**Comment by sanelkukic** [comment]
dis shit ded no more updates lol

**Comment by v1tal** [comment]
lol dab
